[package]
name = "crossvault"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
enum-derived = "0.9.2"
env_logger = "0.11.8"
log = "0.4.28"
rand = "0.9.2"
random_word = { version = "0.5.2", features = ["en"] }
